### PR TITLE
Portuguese translations update

### PR DESCRIPTION
**Pull request by didas72**
Due to some differences between Portuguese from Portugal (pt-PT) and from Brazil (pt-BR) a new language file was created `br.json` with the old contents of `pt.json` and the Portuguese one was updated to better match the language.
There were some inadequate translations (now present in br.json) that could be corrected too, but for now I'm only submitting the changes in `pt.json`.

### CODE REVIEW

**Comment by janstehno** [comment]
Wow, I did not even expect someone to work directly with the GitHub. Thank you so much for this. However I will probably have to merge it with some other changes rather than merge it right away.

One question. The game is using (as I understand it) the Brazillian language. Am I able to use it as Portuguese one as well? Or should I just use English?

**Comment by didas72** [comment]
I'm not sure if this is what you're asking but you could add Portuguese-PT as a new language or you can just set it to the only portuguese. Both Portuguese and Brazillian people understand both "versions" of the language so you can keep the separate or use only one as you wish

**Comment by janstehno** [comment]
Well I have no problems using both files for the UI. I was just asking if I am able to use the game's Brazillian translations with both yours UI translation files `br.json` and `pt.json`. But, as you are saying, both people will understand, then there should be no problem to do it like this. Hope this is more clear.

**Comment by didas72** [comment]
I just added the br.json to store the original trabslation, since it was closer to Brazilian Portuguese but it would probably be sinpler to just use the update pt.json and remove the br one for simplicity.

**Comment by janstehno** [comment]
So, I will use both files in the end. And as I have to do some other specific changes I have to close this request. However I thank you so much for this. It is a big help and I appreciate it. If you would like to be credited in the future, just let me know.

**Pull request closed without merging**
